### ISSUE TITLE
Failovers and Sentinel

### ISSUE THREAD

**Issue by Alex-Mussell** [pivotal-cf/shared-redis-release#18]
As there doesn't seem to be a sentinel job, how would someone failover if the master node fails? The spec file does reference Sentinel once, but there is no release associated with the deployment. Should there be a manual failover? 

Thanks for your help.

**Comment by MirahImage** [comment]
This is a multi-tennant offering of many single node redis instances. There is no clustering or high availability. Hence, the lack of sentinel job.
