### ISSUE TITLE
redis-backups release

### ISSUE THREAD

**Issue by Alex-Mussell** [pivotal-cf/shared-redis-release#22]
Hello,

In the deployment.yml there are jobs which reference the redis-backups release. Where is this release? Is it a private repo? 

Thanks!

**Comment by MirahImage** [comment]
Thanks for bringing this to our attention! Yes, it's a private repo, so we've removed that from the manifest.

**Comment by Alex-Mussell** [comment]
I thought as much. Thanks for the swift response and fix. It's appreciated.

Cheers

**Comment by Alex-Mussell** [comment]
Any idea on when this will be versioned and not off master?

**Comment by MirahImage** [comment]
Hi, we hadn't noticed, but our pipeline had stopped updating the releases at some point. Hopefully we've corrected this now, and you should be able to consume stable releases again.
